# Dockerfile

FROM alpine:latest

MAINTAINER me@nalbam.com

RUN apk --no-cache update && \
    apk --no-cache add gcc git zip curl docker groff less python python-dev py-pip && \
    pip install awscli gcloud && \
    rm -rf /var/cache/apk/*
