# Dockerfile

FROM maven:alpine

MAINTAINER me@nalbam.com

RUN apk --no-cache update && \
    apk --no-cache add git zip curl docker && \
    rm -rf /var/cache/apk/*\

COPY extra/settings.xml /root/.m2/settings.xml

WORKDIR /root

ENTRYPOINT ["mvn"]
CMD ["--help"]
