# Dockerfile

FROM golang:alpine

MAINTAINER me@nalbam.com

RUN apk --no-cache update && \
    apk --no-cache add git zip curl docker && \
    rm -rf /var/cache/apk/*

ENTRYPOINT ["go"]
CMD ["--help"]
