# Dockerfile

FROM maven:alpine

MAINTAINER me@nalbam.com

RUN apk --no-cache update && \
    apk --no-cache add git zip curl docker openssl ca-certificates && \
    rm -rf /var/cache/apk/*

COPY extra/settings.xml /root/.m2/

WORKDIR /root
