# Dockerfile

FROM maven:alpine

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk --no-cache update && \
    apk --no-cache add git zip curl docker bash openssl ca-certificates && \
    rm -rf /var/cache/apk/*

COPY extra/settings.xml /root/.m2/

WORKDIR /root
