# Dockerfile

FROM ubuntu:latest

MAINTAINER me@nalbam.com

RUN add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git zip curl wget docker python-pip nodejs openjdk-8-jdk maven && \
    pip install awscli gcloud ansible

CMD /bin/bash
