# Dockerfile

FROM alpine:latest

RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo 'Asia/Seoul' > /etc/timezone

RUN apk --no-cache update && \
    apk --no-cache add git zip curl docker bash openssl ca-certificates && \
    rm -rf /var/cache/apk/*

WORKDIR /root
