# Dockerfile

FROM docker:latest

ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk --no-cache add git curl bash openssl ca-certificates && \
    rm -rf /var/cache/apk/*
